version: "3.9"
services:
    bot:
        build: .
        container_name: 'bot'
        restart: "unless-stopped"
        command: sh -c "python3 -m src.bot"
        depends_on:
            - db
            - redis
            - migrations

    migrations:
        build: .
        container_name: 'migrations'
        restart: "no"
        command: sh -c "alembic upgrade head"
        depends_on:
            - db
            
    db:
        image: postgres:16.0-alpine3.18
        container_name: "database"
        restart: "unless-stopped"
        env_file: configs/db.env
        volumes:
            - "/hotel-bot-db-data:/var/lib/postgresql/data"

    redis:
        image: redis:7.2.4-alpine
        container_name: "redis"
        restart: "unless-stopped"
        volumes:
            - "/hotel-bot/redis/config:/usr/local/etc/redis"
            - "/hotel-bot/redis/data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
