version: "3.9"
services:
    bot:
        build: .
        container_name: 'bot'
        restart: "unless-stopped"
        command: sh -c "python3 -m src.bot"
        depends_on:
            - db
            - migrations

    migrations:
        build: .
        container_name: 'migrations'
        restart: "unless-stopped"
        command: sh -c "alembic upgrade head"
        depends_on:
            - db
            
    db:
        image: postgres:16.0-alpine3.18
        container_name: 'database'
        restart: "always"
        env_file: configs/db.env
        volumes:
        - /pgsqldata:/var/lib/postgresql/data
        ports:
        - "5432:5432"

volumes:
    hotel-bot-db-data:
